### ISSUE TITLE
Undefined function PyramidInv

### ISSUE THREAD

**Issue by aoom12** [charlesmillard/VDAMP#1]
Hi,

I am having the following issue when running your code. The pyramidInv.m file seems to be missing. 

Thank you!
```
Undefined function or variable 'pyramidInv'.

Error in VDAMP (line 293)
        xk_tilde = multiscaleRecon(pyramidInv(hist.C_thr(:,:,iter), opts.scales));

Error in demo1_just_VDAMP (line 47)
[x_hat, hist]  = VDAMP(dcoil,  mask, prob_map, var0, x0, opts);
```

**Comment by charlesmillard** [comment]
Hi,

Thanks for pointing that out. I've added the pyramidInv.m file - everything should be working fine now!

Please feel free to get in touch with any more questions you have.

Thanks,
Charles


________________________________
